name: Build BeatSync Monorepo

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies (monorepo)
        run: bun install
              - name: Build web app
        run: bun run build --filter=web

      - name: Build server app
        run: bun run build --filter=server


      - name: Upload frontend (apps/web/dist)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: apps/web/dist

      - name: Upload backend (apps/server)
        uses: actions/upload-artifact@v4
        with:
          name: backend-server
          path: apps/server
